name: download_genomes
channels:
  - conda-forge
  - defaults
dependencies:
  # Used for retrieving genomes from NCBI
  - ncbi-datasets-cli = 13.33.0
  # Used for parsing "datasets download genome taxon" output .jsonl files
  - pydantic = 1.9.1
  # Type hinting with e.g. list instead of typing.List requires >= 3.9
  - python >= 3.9
